### PR TITLE
provide metrics for each route of app individually #25 proposal

### PR DESCRIPTION
**Pull request by scalway**
I use similar (not same) implementation in my own code. 
It just map every route pattern to its own metrics. 
There could be nicer way to do that (e.g. "controller.Controller.methodName").
Not sure if it is efficient enough, but I have no time to test it more carefully. What do you think?

### CODE REVIEW

**Comment by liorhar** [comment]
makes sense, though we're working on adjust this plugin to play module see #45 so it will have to wait until after that PR is merged.

**Comment by devsprint** [comment]
Are there any plans to merge this pull requests soon?

**Comment by scalway** [comment]
this pull request probably don't fit anymore (play framework version was bumped to 2.4). This is simple code and could be used just by copying them(maybe it is better solution, because it allows you to customize metrics) 

I have no time now to test it and bump this pull request... sorry.

**Comment by mosheeshel** [comment]
@rannissim , you think this idea is still relevant? Worth play(in) with a bit :smile: ?

**Comment by AvihayTsayeg** [comment]
@mosheeshel , @rannisim 
Lets give it a try ...

**Comment by rannisim** [comment]
@mosheeshel - Something didn't work with the mention so i didn't see this till now.
I think this is definitely worth checking, tho i'm not so sure if the code changes are relevant to play 2.6 as this was added for an older play version.

**Comment by mosheeshel** [comment]
retest this please

**Comment by mosheeshel** [comment]
@rannisim - obviously this PR as is can't be merged as is, talking about the concept.

**Pull request closed without merging**
