### PR TITLE
update scala and play versions

### PR DESCRIPTION
**Pull request by joprice**

### CODE REVIEW

**Comment by liorhar** [comment]
thanks for the PR, I think it's no longer relevant now that we support 2.4 with #37

**Comment by joprice** [comment]
So Play23 support is discontinued? This will force me to fork the library, since I won't be able to migrate to 24 for a few months.

**Comment by liorhar** [comment]
version 2.3.0_0.2.1 which supports play 2.3 is still available, you can use that. but yes, I can't support all play versions.

**Comment by joprice** [comment]
OK. Good to know Thanks

**Pull request closed without merging**
