### PR TITLE
Implement as Play Module rather than Plugin

### PR DESCRIPTION
**Pull request by edvakf**
Plugins are deprecated as of Play 2.4, so I converted the Plugin into a Module. Nearly everything was rewritten, but the logic is still the same.

refs https://github.com/kenshoo/metrics-play/issues/44

### CODE REVIEW

**Comment by edvakf** [comment]
I haven't tested it with Java, but it should work because the MetricsFilter is not a Scala object any more. 

I also got rid of the capability of configuring `knownStatuses` and `labelPrefix` which I'd like to discuss if you think it's important.

**Comment by liorhar** [comment]
thx, good job.
re prefix & statuses I agree it's an esoteric use case (we're not using it) however if I once accepted it see #30 then it would be a pity to drop and break compatibility.

**Comment by edvakf** [comment]
I could successfully configure `labelPrefix` and `knownStatuses` by adding a file like this

```
package myapp

import javax.inject.Inject

import com.kenshoo.play.metrics.{MetricsImpl, MetricsFilter, Metrics, MetricsFilterImpl}
import play.api.http.Status
import play.api.inject.Module
import play.api.{Configuration, Environment}

class MyMetricsFilter @Inject() (metrics: Metrics) extends MetricsFilterImpl(metrics) {
  override def labelPrefix: String = "foobar"

  override def knownStatuses = Seq(Status.OK)
}

class MyMetricsModule extends Module {
  def bindings(environment: Environment, configuration: Configuration) = {
    Seq(
      bind[MetricsFilter].to[MyMetricsFilter].eagerly,
      bind[Metrics].to[MetricsImpl].eagerly
    )
  }
}
```

and add the below to application.conf

```
play.modules.enabled+="myapp.MyMetricsModule"
```

instead of

```
play.modules.enabled+="com.kenshoo.play.metrics.PlayModule"
```

**Comment by edvakf** [comment]
I've added that usage to README.

**Comment by liorhar** [comment]
thx

**Comment by liorhar** [comment]
released to maven

**Pull request merged**
